[package]
name = "disllm"
version = "0.1.0"
edition = "2021"

[dependencies] 
llm = { git = "https://github.com/rustformers/llm" , branch = "main", features = ["clblast"] } # 
rand = "0.8.5"
tokio = { version = "1.38.0", features = ["full"] }

[profiler.dev.package.ggml.sys]
opt-level = 5
